spring:

  devtools:
    restart:
      enabled: false
    # exclude:
      #  static/**, public/**

  thymeleaf:
    cache: false


  webflux:
    hiddenmethod:
      filter:
        enabled: true

  mongodb:
    embedded:
      version: 3.5.5

server:
  port: 8080

logging:
  level:
    web: DEBUG